---
title: "Final report"
author: "An Bui, Sam Csik"
date: "11/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
Clean shit only!

```{r, include = FALSE}
# load required packages
library(tidyverse)
library(car)
library(vcdExtra)
library(kableExtra)
library(onewaytests)
library(wesanderson)

# read in lobster_size_abundance.csv file and get into tidy format
size_abund <- read_csv("lobster_size_abundance.csv")

abund <- as.data.frame(size_abund) %>% 
  expand.dft(freq = "COUNT") # expands freq. table to df representing individual obs. in the table

# read in lobster_traps.csv file and get into tidy format
traps_master <- read_csv("lobster_traps.csv")

traps <- as.data.frame(traps_master) %>% 
  expand.dft(freq = "TRAPS")
```


```{r}
# PART 1. DESCRIBE TRENDS IN LOBSTER ABUNDANCE AND FISHING PRESSURE AT THE 5 LOCATIONS FROM 2012-2017

#############################
#  calculate mean abundance by year for each site
##############################
abund_by_yearssite <- abund %>% 
  group_by(YEAR, SITE) %>% # group by year, then site
  summarize(
    count = length(SIZE) # sample size by site
  ) %>% 
  mutate(site_full = case_when( # expand to full length names
      SITE == "AQUE" ~ "Arroyo Quemado",
      SITE == "CARP" ~ "Carpinteria",
      SITE == "IVEE" ~ "Isla Vista",
      SITE == "MOHK" ~ "Mohawk Reef",
      SITE == "NAPL" ~ "Naples Reef"
    )
  ) %>% 
  select(YEAR, site_full, count) # select and reorder columns

##############################
#  calculate mean fishing pressure by year for each site
##############################

traps_by_yearssite <- traps %>% 
  select(YEAR, SITE, SWATH_START, SWATH_END) %>% 
  filter(SITE == "AQUE" | SITE == "CARP" | SITE == "IVEE" | SITE == "MOHK" | SITE == "NAPL") %>% 
  group_by(YEAR, SITE) %>% # group by year, then site
  summarize(
    count = length(SWATH_START) # number of traps by site
  ) %>% 
  mutate(site_full = case_when( # expand to full length names
      SITE == "AQUE" ~ "Arroyo Quemado",
      SITE == "CARP" ~ "Carpinteria",
      SITE == "IVEE" ~ "Isla Vista",
      SITE == "MOHK" ~ "Mohawk Reef",
      SITE == "NAPL" ~ "Naples Reef"
    )
  ) %>% 
  select(YEAR, site_full, count) # select and reorder columns

##############################
# plot trends in lobster abundance AND fishing pressure by site thorugh time TOGETHER on same plot
##############################

# FIGURE OUT SECOND Y AXIS FOR TRAP #

abund_traps_plot <- ggplot(abund_by_yearssite, aes(x = YEAR, y = count)) +
  geom_point(aes(color = site_full)) +
  geom_line(aes(color = site_full)) +
  geom_point(data = traps_by_yearssite, aes(color = site_full)) +
  geom_line(data = traps_by_yearssite, linetype = "dashed", aes(color = site_full)) +
  #scale_y_continuous(sec.axis = trans = NULL, name = "# Traps", breaks = NULL)) +
  theme_classic() +
  theme(axis.text = element_text(color = "black"), 
          panel.border = element_rect(colour = "black", fill=NA, size=0.7), 
          legend.position = "none") + 
  facet_wrap(~site_full) +
  labs(x = "Year", y = "Lobster Counts")  +
  scale_color_manual(values = wes_palette(n = 5, name = "Cavalcanti1"))

abund_traps_plot
```

```{r}
# PART 2. COMPARE MEAN LOBSTER SIZE BY SITE IN 2017

##############################
# size table
##############################
abund_2017 <- abund %>% 
  filter(YEAR == "2017") %>% 
  mutate(site_full = case_when( # expand to full length names
      SITE == "AQUE" ~ "Arroyo Quemado",
      SITE == "CARP" ~ "Carpinteria",
      SITE == "IVEE" ~ "Isla Vista",
      SITE == "MOHK" ~ "Mohawk Reef",
      SITE == "NAPL" ~ "Naples Reef"
    )
  ) %>% 
  select(YEAR, SITE, site_full, SIZE)

size_table_2017 <- abund_2017 %>% 
  group_by(SITE) %>% 
  summarize(
    mean = round(mean(SIZE), 2),
    sd = round(sd(SIZE), 2),
    n = length(SIZE)
    ) %>% 
  mutate(
    full_site = case_when(
      SITE == "AQUE" ~ "Arroyo Quemado",
      SITE == "IVEE" ~ "Isla Vista", 
      SITE == "MOHK" ~ "Mohawk",
      SITE == "CARP" ~ "Carpinteria",
      SITE == "NAPL" ~ "Naples Reef"
    )
  ) %>% 
  select(full_site, mean, sd, n)

size_table_2017$full_site <- factor(size_table_2017$full_site, levels = c("Isla Vista", "Naples Reef", "Arroyo Quemado", "Mohawk", "Carpinteria"))

size_table_2017_columns = c("Site", "Mean length", "Standard deviation", "Sample size")

kable(size_table_2017,
      col.names = size_table_2017_columns) %>% 
  kable_styling(bootstrap_options = "striped")

##############################
# box and whisker plot of size
##############################

size_2017_boxplot <- ggplot(abund_2017, aes(x = site_full, y = SIZE)) +
  geom_boxplot(aes(fill = site_full)) +
  #geom_jitter() +
  theme_classic() +
  theme(axis.text = element_text(color = "black"), 
          panel.border = element_rect(colour = "black", fill=NA, size=0.8), 
          legend.position = "none") +
  labs(x = "Site", y = "Carapace Length (mm)") +
  scale_fill_manual(values = wes_palette(n = 5, name = "Cavalcanti1"))

size_2017_boxplot

##############################
# test for variances, ANOVA, Tukey's HSD
##############################

lob_variances <- abund_2017 %>% 
  group_by(SITE) %>% 
  summarize(
    lob_var = var(SIZE)
  )

lob_variances 
# largest variance is no greater than 4x smallest variance

size_anova <- aov(SIZE ~ SITE, data = abund_2017)
summary(size_anova)

size_ph <- TukeyHSD(size_anova)
size_ph 
# so the only ones that are different are NAPL-CARP and NAPL-IVEE
```

```{r}
# PART 3. AT IVEE AND NAPL (MPAs), HOW DO LOBSTER SIZES IN 2012 AND 2017 COMPARE? AT NON-MPA SITES?

##############################
# comparing 2012 and 2017 at IVEE and NAPL
##############################

size_ivee_2012 <- abund %>%
  filter(SITE == "IVEE",
         YEAR == "2012") %>% 
  pull(SIZE)

size_ivee_2017 <- abund %>% 
  filter(SITE == "IVEE",
         YEAR == "2012") %>% 
  pull(SIZE)

size_napl_2012 <- abund %>%
  filter(SITE == "NAPL",
         YEAR == "2012") %>% 
  pull(SIZE)

size_napl_2017 <- abund %>% 
  filter(SITE == "NAPL",
         YEAR == "2017") %>% 
  pull(SIZE)

# idk what's going on with IVEE but did it anyway
ivee_t <- t.test(size_ivee_2012, size_ivee_2017, var.equal = TRUE)
ivee_t
# p value = 1?? lob means are not significantly different between 2012 and 2017 at IVEE

napl_t <- t.test(size_napl_2012, size_napl_2017, var.equal = TRUE)
napl_t
# p value = 0.5373, lob means are not significantly different between 2012 and 2017 at NAPL

# In a report, maybe: Between 2012 and 2017, mean lobster size did not change significantly at either Isla Vista (t(df) = statistic, p = statistic, a = 0.05) or Naples Reef (t(df) = statistic, p = statistic, a = 0.05).

```

```{r}
# PART 4. WHAT PROPORTION OF OBSERVED LOBSTERS AT EACH SITE ARE ABOVE THE LEGAL MINIMUM (82.6mm)
```

